base/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('shop/', include('shop.urls')),
    path('req/', include('requestdataapp.urls')),
    path('myauth/', include('myauth.urls')),
]


if settings.DEBUG:
    urlpatterns.extend(
        static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
    )

myauth/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView
from . import views

app_name = 'myauth'

urlpatterns = [
    #path('login/', login_view, name = 'login')
    path('login/',LoginView.as_view(template_name = 'myauth/login.html', redirect_authenticated_user = True), name= 'login'),
    path('logout/', views.logoutView, name = 'logout'),
    path('cookie/get/', views.get_cookie_view, name = 'cookie-get'),
    path('foo-bar/', views.FooBarView.as_view(), name = 'foo-bar'),
    path('profile/edit/<str:slug>/', views.AboutMeViewUpdate.as_view(), name='profileedit'),
    path('profile/<str:slug>/', views.AboutMeView.as_view(), name='profile'),
    path('register/', views.RegisterView.as_view(), name='register')
]

myauth/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse, reverse_lazy
from django.template.defaultfilters import slugify
# Create your models here.

class Profile(models.Model):
    class Meta:
        verbose_name_plural = 'Профили пользователей'
        ordering = ['slug',]
    user = models.OneToOneField(User, on_delete = models.CASCADE)
    choiceuniversity = [
        ('KFU','Казанский Федеральный Университет'),
        ('KAI','Казанский Авиационный Институт'),
        ('КНИТУ','Казанский национальный исследовательский технологический университет'),
        ('КГЭУ','Казанский государственный экономический университет'),
        ('Другой','Нет в списке')
    ]
    university = models.CharField(max_length=255, choices=choiceuniversity, blank = True)
    agreement_accepted = models.BooleanField(default = False)
    slug = models.SlugField(max_length=255, unique=True, db_index=True, blank=True, verbose_name="URL")
    def __str__(self):
        return str(self.user)
    

    #Создание slug для аккаунта
    def save(self, *args, **kwargs):
        
        self.slug = slugify(self.user.username)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('myauth:profile', kwargs={'slug': self.slug})

myauth/forms.py
from django import forms


class RegisterFrom(forms.Form):
    login = forms.CharField(label = 'Введите желаемый логин')
    name = forms.CharField(label='Введите ваше имя')
    surname = forms.CharField(label='Введите фамилию')

myauth/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User, Group,Permission
from django.http import HttpRequest, HttpResponse, HttpResponseRedirect, JsonResponse
from django.urls import reverse, reverse_lazy
from django.views.generic import TemplateView, CreateView, UpdateView, DetailView
from django.views import View
from . import models
# Create your views here.

def login_view(request: HttpRequest):
    if request.method == 'GET':
        if request.user.is_authenticated:
            return redirect('/shop/')
        
        return render(request, 'myauth/login.html')
    
    username = request.POST['username']
    password = request.POST['password']


    user = authenticate(request, username = username, password = password)
    
    if user is not None:
        login(request,user)
        return redirect('/shop/')
    
    return render(request, 'myauth/login.html', {'error': 'Invalid login credentials'})

def logoutView(request:HttpRequest):
    # template_name = 'myauth/logout.html'
    logout(request)
    return redirect(reverse('myauth:login'))
        

class AboutMeView(DetailView):
    model = models.Profile
    template_name = 'myauth/user_info.html'
    context_object_name = 'profile'
 

class AboutMeViewUpdate(UpdateView):
    template_name = 'myauth/user_info_edit.html'
    model = models.Profile
    fields = ('university','slug')
    success_url = reverse_lazy('myauth:profileedit')
    def get_success_url(self):
        return reverse('myauth:profile', kwargs={'slug': self.object.slug})


class RegisterView(CreateView):
    form_class = UserCreationForm
    template_name = 'myauth/register.html'
    success_url = reverse_lazy('shop:index')

    def form_valid(self, form): # Переопределение form_valid, дабы после регистрации осуществлять автоматический вход на аккаунт
        response = super().form_valid(form)
        models.Profile.objects.create(user = self.object)
        username = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password1')
        user = authenticate(self.request, username=username, password = password)
        login(self.request, user)
        return response


def get_cookie_view(request: HttpRequest):
    value = request.COOKIES.get("fizz", 'default value')
    return HttpResponse(f'Cookie value = {value}')

class FooBarView(View):
    def get(self, request: HttpRequest) -> JsonResponse:
        return JsonResponse({'foo': 'bar', 'spam': 'eggs'})

templates/myauth/base.html
<!DOCTYPE html>
<html lang="ru">
{%load static%}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link rel="stylesheet" href="{% static 'css/main.css'%}" type="text/css">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@500&display=swap" rel="stylesheet">
    <title>PET project</title>
</head>
<body>
   <header> 
    </header>
    <main class="container">
        {% block body %}

        {% endblock %}
    </main>
</body>
</html>

templates/myauth/login.html
{% extends "myauth/base.html" %}
{% block body %}
<div class = 'loginform'>
<form method='post'>
    {% csrf_token %}
    {% if error %}
    {{error}}
    {% endif %}
            <div class = "formalogin"></div>
        <div class="loginarea">
            {{form.as_p}}
        </div>


        <div class="submitreg">
            <button type='submit', class = "savebutton", class= "center">Войти</button>
        </form>
        </div>
            </div>

        </div>
    </form>
</div>
</div>



{% endblock body %}

templates/myauth/register.html
{% extends "myauth/base.html" %}
{% block body %}

<div class = 'loginform'>
    <form method='post'>
        {% csrf_token %}
        {% if error %}
        {{error}}
        {% endif %}
                <div class = "formalogin"></div>
            <div class="loginarea">
                {{form.as_p}}
            </div>
    
    
            <div class="submitreg">
                <button type='submit', class = "savebutton", class= "center">Зарегестрироваться</button>
            </form>
            </div>
                </div>
    
            </div>
        </form>
    </div>
    </div>

{% endblock body %}

templates/myauth/user_info.html
{% extends "myauth/base.html" %}
{% block body %}

{% if user.is_authenticated %}
<div class = 'loginform'>
<label>Ваш логин: {{user.username}}</label>
<label>Ваш e-mail: {{user.email}}</label>
<label>Ваш университет: {{user.profile.university}}</label>
            <div class="submitreg">
                <a class = "savebutton", class= "center", href={% url "myauth:profileedit" profile.slug%}>Изменить</a>
            <a class = 'pos' href={% url "myauth:logout" %}> Выйти</a>




{% else %}
<h1> Вы не выполнили вход</h1>
{% endif %}

{% endblock body %}

templates/myauth/user_info_edit.html
{% extends "myauth/base.html" %}
{% block body %}

{% if user.is_authenticated %}
<div class = 'loginform'>
<label>Ваш логин: {{username}}</label>
<label>Ваш e-mail: {{user.email}}</label>
<label>Ваш университет: {{user.profile.university}}</label>
        <form method='post'>
        {% csrf_token %}
    
            <div class="UserBioarea">
                {{form.as_p}}
            </div>
            <div class="submitreg">
                <button type='submit', class = "savebutton", class= "center">Сохранить</button>
            </form>
            </div>
            <a class = 'pos' href={% url "myauth:logout" %}> Выйти</a>

                </div>
                
            </div>
            
        </form>
        
    </div>



{% else %}
<h1> Вы не выполнили вход</h1>
{% endif %}

{% endblock body %}