base/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('shop/', include('shop.urls')),
    path('req/', include('requestdataapp.urls')),
    path('myauth/', include('myauth.urls')),
]


if settings.DEBUG:
    urlpatterns.extend(
        static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
    )

shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.shopItems.as_view(), name='index'),
    path('create',views.shopCreate.as_view(), name='shopCreate'),
    path('<int:pk>', views.ShopDetailView.as_view(), name = 'shop_item'),
    path('<int:pk>', views.CommentCreate.as_view(), name = 'shop_item'),
    path('update/<int:pk>', views.shopitemupdate.as_view(), name = 'shop_item_update'),
    path('delete/<int:pk>', views.ShopItemDelete.as_view(), name = 'shop_item_delete'),
    path('order/<int:pk>', views.OrderDetail.as_view(), name = 'order'),
    path('comment/delete/<int:pk>', views.CommentDelete.as_view(), name = 'comment_delete'),
    path('products/export/', views.ProductDataExportView.as_view(), name = 'product_export')
]

shop/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

# Create your models here.


def product_image_directory(instance: "Course", filename: str) -> str:
    return "products/product_{title}/preview/{filename}".format(
        title = instance.title,
        filename = filename,
    )

class Category(models.Model):

    class Meta:
        verbose_name_plural = 'Категории товаров'
    title = models.CharField(max_length=255)
    created_at = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.title


class Course(models.Model):
    class Meta:
        ordering = ['title'] # Сортировка по полю title
        verbose_name_plural = "Товары" # Указание как будет выглядить во мн.ч

    title = models.CharField(max_length=255)
    about = models.TextField(null=False, blank=True)
    price = models.IntegerField()
    check_qty = models.IntegerField()
    reviews_qty = models.IntegerField()
    Category = models.ForeignKey(Category, on_delete=models.CASCADE)
    archived = models.BooleanField(default=False)
    created_at = models.DateTimeField(default=timezone.now)
    preview = models.ImageField(null = True, blank = True, upload_to = product_image_directory)

    def __str__(self):
        return self.title
    
class Order(models.Model):
    class Meta:
        verbose_name_plural = 'Заказы'
    choicesorderstatus = [
        ('Accepted','Заказ принят'),
        ('paid','Заказ оплачен'),
        ('in work','Выполняется'),
        ('comleted','Выполнен'),
    ]
    coursetype = models.ForeignKey(Course, on_delete=models.PROTECT)
    date = models.DateTimeField(auto_now_add=True, verbose_name="Дата заказа")
    status = models.CharField(max_length=255, choices=choicesorderstatus)
    user = models.ForeignKey(User, on_delete=models.PROTECT)
    receipt = models.FileField(null = True, upload_to = 'orders/receipts/')

class Comment(models.Model):
    class Meta:
        verbose_name_plural = 'Комментарии'
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    coursecom = models.ForeignKey(Course, on_delete = models.CASCADE)
    commenttext = models.TextField(null = False, blank = False)
    parent_id = models.IntegerField(null = True, blank = True) 
    
    def __str__(self):
        return self.commenttext

shop/forms.py
from django import forms
from .models import Comment

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['commenttext']

shop/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, Http404, HttpRequest, HttpResponseRedirect, JsonResponse
from django.views import View
from django.shortcuts import redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import TemplateView, ListView, DetailView, CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.views.generic.edit import FormMixin
from . import models
from .forms import CommentForm

# Create your views here.
# class ShopDetailView(View):
#     def get(self, request:HttpRequest, pk:int) -> HttpResponse:
#         course = get_object_or_404(models.Course, pk=pk)
#         return render(request, 'shop/shop_item.html', {'course': course})
    
class ShopDetailView(LoginRequiredMixin,DetailView, CreateView):
    template_name = 'shop/shop_item.html'
    model = models.Course
    context_object_name = 'course'
    form_class = CommentForm


    # Отрисовывание комментариев
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['comments'] = models.Comment.objects.filter(coursecom=self.kwargs['pk']) 
        return context
    

    def post(self, request, *args, **kwargs):
        course = self.get_object()
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.user = request.user
            comment.coursecom = course
            comment.commenttext = form.cleaned_data['commenttext']
            comment.save()
            return redirect('shop:shop_item', pk=course.pk)
        else:
            context = self.get_context_data(object=self.object)
            context['comment_form'] = form
            return self.render_to_response(context)
    
        
    def get_success_url(self):
        return reverse(
            'shop:shop_item',
            kwargs={'pk': self.object.pk}
        )

# class shopItems(TemplateView):
#     template_name = 'shop/courses.html'

#     def get_context_data(self,**kwargs):
#         context = super().get_context_data(**kwargs)
#         context['courses'] = models.Course.objects.all().select_related("Category")
#         #Courses = get_object_or_404(models.Course)
#         #context = {
#             #'courses': Courses
#         #}
#         return context 


class shopItems(ListView):
    template_name = 'shop/courses.html'
    model = models.Course
    context_object_name = 'courses'
    queryset = models.Course.objects.filter(archived = False)


class OrderDetail(DetailView): #PermissionRequiredMixin,
    #permission_required = 'shop.view_order'
    template_name = 'shop/orders.html'
    queryset = (models.Order.objects.select_related('user').prefetch_related('coursetype'))
    model = models.Order


class CommentCreate(CreateView):
    template_name = 'shop/shop_item.html'
    model = models.Comment
    fields = 'commenttext', 
    success_url = reverse_lazy('shop:index')


class shopCreate(CreateView):
    template_name = 'shop/create_items.html'
    model = models.Course
    fields = 'title', 'price','check_qty', 'reviews_qty','preview','Category'
    success_url = reverse_lazy('shop:index')

class shopitemupdate(UpdateView):
    template_name = 'shop/update_items.html'
    model = models.Course
    fields = 'title', 'price','check_qty', 'reviews_qty','Category','archived','about', 'preview'
    success_url = reverse_lazy('shop:shop_item')
    def get_success_url(self):
        return reverse(
            'shop:shop_item',
            kwargs={'pk': self.object.pk}
        )
    

class ShopItemDelete(DeleteView):
    model = models.Course
    success_url = reverse_lazy('shop:index')
    def form_valid(self, form):
        success_url = self.get_success_url()
        self.object.archived = True
        self.object.save()
        return HttpResponseRedirect(success_url)

class CommentDelete(DeleteView):
    model = models.Comment
    success_url = reverse_lazy('shop:index')
    def CommentDelete(request):
        comment = models.Comment.objects.all()
        if comment.user == request.user:
            comment.is_removed == True
            comment.save()
        return reverse_lazy('shop:index')


class ProductDataExportView(View):
    def get(self, request:HttpRequest) -> JsonResponse:
        products = models.Course.objects.order_by('pk').all()
        products_data = [
            {   
                'pk': product.pk,
                'title': product.title,
                'price': product.price

            }
            for product in products
        ]
        return JsonResponse({'products':products_data})

# class ShopIndexView(View):
#     def get(self,request):
#         Courses = models.Course.objects.all().select_related('Category')
#         #return HttpResponse(''.join([str(courses) + '<br>' for courses in Courses]))
#         return render(request, 'shop/courses.html', {'courses':Courses})
# def index(request):
#     Courses = models.Course.objects.all().select_related('Category')
#     #return HttpResponse(''.join([str(courses) + '<br>' for courses in Courses]))
#     return render(request, 'shop/courses.html', {'courses':Courses})

# def shop_item(request, item_id):
#     # try:
#     #     course = models.Course.objects.get(id = item_id)
#     #     return render(request, 'shop_item.html', {'course': course})
#     # except models.Course.DoesNotExist:
#     #     raise Http404()
#     course = get_object_or_404(models.Course, id = item_id)
#     return render(request, 'shop/shop_item.html', {'course': course})

templates/shop/comment.html
{% extends "shop_item.html" %}
{% block comment %}
{% for comment in comments %}
    <div class = 'comment'>
    <h1>Автор: {{comment.user}}</h1>
    <h2>{{comment.commenttext}}</h2>
    </div>
{% endfor %}
{% endblock comment %}

templates/shop/comment_confirm_delete.html
{% extends "base.html" %}
{% block content %}

<h1 class = 'pos'> Вы уверены что хотите удалить комментарий</h1>
<h1 class = 'pos'>{{course.title}}</h1>
<div>
    <form method="post">
        {% csrf_token %}
        {{form.as_p}}
        <div class="submitreg">
            <button type='submit', class = "savebutton", class= "center">Подтвердить</button>
        </div>
    </form>
</div>
{% endblock content %}

templates/shop/course_confirm_delete.html
{% extends "base.html" %}
{% block content %}

<h1 class = 'pos'> Вы уверены что хотите архивировать товар</h1>
<h1 class = 'pos'>{{course.title}}</h1>
<div>
    <form method="post">
        {% csrf_token %}
        {{form.as_p}}
        <div class="submitreg">
            <button type='submit', class = "savebutton", class= "center">Подтвердить</button>
        </div>
    </form>
</div>
{% endblock content %}

templates/shop/courses.html
{% extends "base.html" %}
{% block content %}
<div class = 'showcourses'>
<table class="table mt-5 table-bordered table-striped table-hover ">
    <thead class = "table-dark">
        <tr>
            <th>Название</th>
            <th>Категория</th>
            <th>Цена</th>
            <th>Количество заказов</th>
            <th>Средняя оценка</th>
            <th>Был создан:</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        {% for course in courses%}
        <tr>
            <td>
            <a href={% url "shop:shop_item" course.id %}  class="text-decoration-none">{{course.title}}</a>
            </td>
            <td>{{course.Category.title}}</td>
            <td>{{course.price}}</td>
            <td>{{course.check_qty}}</td>
            <td>{{course.reviews_qty}}</td>
            <td>{{course.Category.created_at}}</td>
            <td><button class = "btn btn-primary">Заказать</button></td>
        </tr>
        {% endfor %}
    </tbody>
</table>
</div>
{% endblock %}

templates/shop/create_items.html
{% extends "base.html" %}
{% block content %}
<h1 class='pos'>Форма создания новых продуктов</h1>
<div class = 'bioform'>
        <form method='post', enctype = "multipart/form-data">
        {% csrf_token %}
    
                <div class = "formaabout"></div>
            <div class="UserBioarea">
                {{form.as_p}}
            </div>
            <div class="submitreg">
                <button type='submit', class = "savebutton", class= "center">Создать</button>
            </form>
            </div>
                </div>
    
            </div>
        </form>
    </div>

{% endblock content %}

templates/shop/orders.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<h1>Order # {{order.pk}}</h1>
<h2>Details</h2>
<h1>Дата заказа: {{order.date}}</h1>
<h1>Статус: {{order.status}}</h1>
<h1>Заказан выполняет: {{order.user}}</h1>
{% endblock content %}

templates/shop/shop_item.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<link rel="stylesheet" href="{% static 'css/main.css'%}" type="text/css">
<div class='items'>
{% if course.preview %}
<div class=img>
    <img src={{course.preview.url}} width="500" height="500">
</div>
{% endif %}
<div class='itemsabout'>
<h1 class="coursename">{{course.title}}</h1>
<div class='itemsinfo'>{{course.about}}</div>
<div class='itemsfooter'>
<h2>Цена {{course.price}} руб. <h2>
<p>Количество заказавших данную работу: {{course.check_qty}}<p>
<div class='positionbutton'>
<button class = "buybutton">Заказать</button>
</div>
</div>
<div class = 'divtools'>
<a href="{% url 'shop:shopCreate' %}">Создать новый продукт</a>
<p></p>
<a href="{% url 'shop:shop_item_update' pk=course.pk %}">Изменить</a>
<p></p>
<a href="{% url 'shop:shop_item_delete' pk=course.pk %}">Архивировать</a>
<p></p>
<a href="{% url 'shop:index' %}">Вернуться назад</a>
<p></p>
<div>
</div>
</div>
</div>
</div>


<p class="comment-divider"></p>
<p>Комментарии:</p>
<form method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <button type='submit', class = "savebutton", class= "center">Создать</button>
</form>
{% for comment in comments %}
    <div class = 'comment'>
    <p class = 'comment-user'>Автор: {{comment.user.username}}</p>
    <p class = 'comment-text'>{{comment.commenttext}}</p>
    </div>
    {% if user.id == comment.user_id %}
        <a href="{% url "shop:comment_delete" pk=comment.pk %}">Удалить</a>
    {% endif %}
{% endfor %}
<div>

</div>
{% endblock %}

templates/shop/update_items.html
{% extends "base.html" %}
{% block content %}
<h1 class='pos'>Форма редактирования продуктов</h1>
<div class = 'bioform'>
        <form method='post', enctype = "multipart/form-data">
        {% csrf_token %}
    
                <div class = "formaabout"></div>
            <div class="UserBioarea">
                {{form.as_p}}
            </div>
            <div class="submitreg">
                <button type='submit', class = "savebutton", class= "center">Изменить</button>
            </form>
            </div>
                </div>
            </div>
        </form>
    </div>

{% endblock content %}