base/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('shop/', include('shop.urls')),
    path('req/', include('requestdataapp.urls')),
    path('myauth/', include('myauth.urls')),
]


if settings.DEBUG:
    urlpatterns.extend(
        static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
    )

shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.shopItems.as_view(), name='index'),
    path('create',views.shopCreate.as_view(), name='shopCreate'),
    path('<int:pk>', views.ShopDetailView.as_view(), name = 'shop_item'),
    path('<int:pk>', views.CommentCreate.as_view(), name = 'shop_item'),
    path('update/<int:pk>', views.shopitemupdate.as_view(), name = 'shop_item_update'),
    path('delete/<int:pk>', views.ShopItemDelete.as_view(), name = 'shop_item_delete'),
    path('order/<int:pk>', views.OrderDetail.as_view(), name = 'order'),
    path('comment/delete/<int:pk>', views.CommentDelete.as_view(), name = 'comment_delete'),
    path('products/export/', views.ProductDataExportView.as_view(), name = 'product_export')
]

templates/base.html
<!DOCTYPE html>
<html lang="ru">
{%load static%}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link rel="stylesheet" href="{% static 'css/main.css'%}" type="text/css">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@500&display=swap" rel="stylesheet">
    <title>PET project</title>
</head>
<body>
   <header> 
    <nav class="navbar navbar-dark bg-dark">
        <div class="container">
            <a href={% url "shop:index" %} class="navbar-brand">Заказать работу</a>
            <a href= class="navbar-brand">Админ-панель</a>
        </div>
    </nav>
    </header>
    <main class="container">
        {% block content %}
        {% endblock %}
    </main>
    <div class = 'footer'></div>
    <p class="comment-divider"></p>
    <p>footer, coming soon...</p>
</body>
</html>

templates/index.html
<!DOCTYPE html>
<html lang="en">
 <head>
    <meta charset="UTF-8">
    <title>PET</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@100&family=Roboto+Condensed&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="main.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
</head>
<body>
    <header id="header" class="header">
            <div class="header_section">
                <div class="header_item headerButton"><a href=".//site.html">Главная</a></div>
                <div class="header_item headerButton"><a href="#">Новости</a></div>
                <div class="header_item headerButton"><a href="https://yandex.ru/pogoda/krugloye-pole">Погода</a></div>
            </div>
            <div class="header_section">
                <div class="header_item headerButton"><a href=".//url/register.html">Войти</a></div>
            </div>

        </div>
    </header>
    <section id="main" class="main">
        <div class="container">
            <div class="post-wrap">
                <div class="post-item">
                <div class="item-content">
                <div class="item-icon group"></div>
                <div class="item-body">
                <h3>Магазин для студентов</h3>
                <p>PET-project с возможность заказать дипломные и курсовые работы</p>
                </div>
                <div class="item-footer">
                <a href="http://127.0.0.1:8000/shop/" class="link"><span>Подробнее</span></a>
                </div>
                </div>
                </div>
                
                <div class="post-item">
                <div class="item-content">
                <div class="item-icon tree"></div>
                <div class="item-body">
                <h3>В разработке</h3>
                <p>В разработке</p>
                </div>
                <div class="item-footer">
                <a href="#" class="link"><span>Подробнее</span></a>
                </div>
                </div>
                </div>
                
                <div class="post-item">
                <div class="item-content">
                <div class="item-icon anchor"></div>
                <div class="item-body">
                <h3>В разработке</h3>
                <p>В разработке</p>
                </div>
                <div class="item-footer">
                <a href="#" class="link"><span>Подробнее</span></a>
                </div>
                </div>
                </div>
                
                <div class="post-item">
                <div class="item-content">
                <div class="item-icon video"></div>
                <div class="item-body">
                <h3>В разработке</h3>
                <p>В разработке</p>
                </div>
                <div class="item-footer">
                <a href="#" class="link"><span>Подробнее</span></a>
                </div>
                </div>
                </div>
                
                <div class="post-item">
                <div class="item-content">
                <div class="item-icon photo"></div>
                <div class="item-body">
                <h3>В разработке</h3>
                <p>В разработке</p>
                </div>
                <div class="item-footer">
                <a href="#" class="link"><span>Подробнее</span></a>
                </div>
                </div>
                </div>
                
                <div class="post-item">
                <div class="item-content">
                <div class="item-icon gift"></div>
                <div class="item-body">
                <h3>В разработке</h3>
                <p>В разработке.</p>
                </div>
                <div class="item-footer">
                <a href="#" class="link"><span>Подробнее</span></a>
                </div>
                </div>
                </div>
                </div>
        </div>
    </section>
    <footer id="footer" class="footer">
        <div class="container">

        </div>
    </footer>
</body>
</html>

templates/test.html
<img src="C:/Users/kadzutokun/Desktop/python%20coding/django%20project/shop/img/coding.png" alt="">